name: CI

on:
  push:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build app
      run: npm run build
    - uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: dist/

  deploy:
    name: Deploy
    if: success()
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: build-artifacts 
    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_APPLICATION_CREDENTIALS }}
        CLI: gsutil
      with:
        args: cp -r build-artifacts gs://gettin-jacked.com
